### ISSUE TITLE
I am trying to modify the init method to the __construct method

### ISSUE THREAD

**Issue by kids-return** [yiisoft/di#69]
https://github.com/yiisoft/di/blob/56489c3515201d8604ebb9f974ce26f0c134a140/src/AbstractContainer.php#L355

https://github.com/yiisoft/di/blob/56489c3515201d8604ebb9f974ce26f0c134a140/src/AbstractContainer.php#L359

Because the assignment of the attribute is after `__construct()`
This will cause the settings in the `__construct()` to be used in the configuration file that cannot be applied to the object.
E.g
```php
    public $db = 'db';
    public function __construct()
    {
        $this->db = Yii::ensureObject($this->db, Connection::class);
    }
```
https://github.com/yiisoft/di/blob/56489c3515201d8604ebb9f974ce26f0c134a140/src/Initiable.php#L12

Is there any plan for the development team?

**Comment by machour** [comment]
CC @hiqsol

**Comment by samdark** [comment]
```php
    public function __construct(Connection $db)
    {
        $this->db = $db;
    }
```

**Comment by kids-return** [comment]
I am trying to change `yii2-queue` to the version of `yii3`

**Comment by samdark** [comment]
Should be something like:

```php
return [
    'queue' => [
        '__class' => \yii\queue\db\Queue::class,
        '__construct()' => [
            Reference::to('db'),
        ],
    ],
];
```

**Comment by hiqsol** [comment]
And even `Reference` is not needed because `ConnectionInterface` is already defined in DI config
https://github.com/yiisoft/db/blob/master/config/common.php#L4

All you need is simply:

```php
return [
    'queue' => [
        '__class' => \yii\queue\db\Queue::class,
    ],
];
```

**Comment by kids-return** [comment]
```php
return [
    \yii\mutex\Mutex::class => \yii\di\Reference::to('mutex'),
    'mutex' => [
        '__class' => \yii\mutex\MysqlMutex::class
    ],
    'queue' => [
        '__class' => \yii\queue\db\Queue::class,
    ],
];
```

```php
    public function __construct(Connection $db, Mutex $mutex)
    {
        $this->db = $db;
        $this->mutex = $mutex;
    }
```
I tried to do this, but there was an error.  : (
```shell
root@84f6fb5775f0:/data/wwwroot/yii3# ./vendor/bin/yii queue/listen --color -v
PHP Fatal error:  Uncaught yii\di\exceptions\InvalidConfigException: Missing required parameter "dsn" when instantiating "PDO". in /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php:455
Stack trace:
#0 /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php(350): yii\di\AbstractContainer->resolveDependencies(Array, Object(ReflectionClass))
#1 /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php(163): yii\di\AbstractContainer->buildFromConfig('PDO', Array)
#2 /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php(132): yii\di\AbstractContainer->buildWithoutDefinition('PDO', Array)
#3 /data/wwwroot/yii3/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('PDO')
#4 /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php(451): yii\di\Container->get('PDO')
#5 /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php(350): yii\di\AbstractContainer->resolveDependencies(Array, Object(ReflectionClass))
#6 /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php in /data/wwwroot/yii3/vendor/yiisoft/di/src/AbstractContainer.php on line 455
```

**Comment by hiqsol** [comment]
You need `ConnectionInterface` not `Connection` in constructor.

**Comment by kids-return** [comment]
This error is caused by `mutex`, I think it should be a bug of mutex package

**Comment by kids-return** [comment]
https://github.com/yiisoft/mutex/blob/878604ac7ebd2ab601f1ac5d8730fe0af6551789/src/MysqlMutex.php#L17

**Comment by hiqsol** [comment]
You need to put DI config for PDO.
You can use something like this:
```php
    \PDO::class => \yii\di\Reference::to('pdo'),
    'pdo' => array_filter([
        '__class'   => \PDO::class,
        'dsn'       => $params['db.type'] . ':dbname=' . $params['db.name']
                        . (!empty($params['db.host']) ? (';host=' . $params['db.host']) : '')
                        . (!empty($params['db.port']) ? (';port=' . $params['db.port']) : ''),
        'username'  => $params['db.user'],
        'password'  => $params['db.password'],
        'options' => $params['db.options'],
    ]),
```

It uses same params as ConnectionInterface: https://github.com/yiisoft/db/blob/master/config/common.php
So `PDO` object will have same config as ConnectionInterface.

**Comment by kids-return** [comment]
The db driver is now working properly.
The following is related configuration
```php
return [
    'app' => [
        'bootstrap' => [
            'queue' => 'queue',
        ],
    ],
    'queue' => [
        '__class' => \yii\queue\db\Queue::class,
        'tableName' => '{{%yii_queue}}'
    ],
    \yii\queue\serializers\SerializerInterface::class => Reference::to('queue.serializer'),
    'queue.serializer' => [
        '__class' => \yii\queue\serializers\PhpSerializer::class,
    ],
    \PDO::class => \yii\di\Reference::to('pdo'),
    'pdo' => [
        '__class'   => \PDO::class,
        '__construct()' => [
            'dsn' => $params['db.dsn'],
            'username'  => $params['db.username'],
            'password'  => $params['db.password'],
            'options' => [],
        ]
    ],
    \yii\mutex\Mutex::class => \yii\di\Reference::to('mutex'),
    'mutex' => [
        '__class' => \yii\mutex\MysqlMutex::class
    ],
];
```
\yii\queue\Queue
```php
    /**
     * @inheritdoc
     */
    public function __construct(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }
```
\yii\queue\db\Queue
```php
    public function __construct(SerializerInterface $serializer, ConnectionInterface $db, Mutex $mutex)
    {
        parent::__construct($serializer);
        $this->db = $db;
        $this->mutex = $mutex;
    }
```
